apiVersion: v1
kind: Pod
metadata:
  name: secpod
spec:
  containers:
    - name: seccont
      image: tomcat
      ports:
        - name: contport
          containerPort: 8080
      env: 
       - name: USER
         valueFrom:
           secretKeyRef:
             name: secfile
             key: user
             optional: false  
