apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomrep
  labels:
    app: ta
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcatapp
  template:
    metadata:
      name: apppod
      labels:
        app: tomcatapp
    spec:
      containers:
        - name: tomcat
          image: imranvisualpath/freshtomapp:V7 
          ports:
            - name: appport
              containerPort: 8080


