apiVersion: v1
kind: Pod
metadata:
  name: volpod
  labels:
    app: volpod
spec:
  containers:
    - name: volcont
      image: imranvisualpath/freshtomapp:V7
      ports:
        - name: cont
          containerPort: 8080
      volumeMounts:
        - mountPath: /root
          name: test
  volumes:
    - name: test
      awsElasticBlockStore:
        volumeID: vol-088876f492c05b514
        fsType: ext4

