---
apiVersion: v1
kind: Pod
metadata:
   name: tomcat
   labels:
     app: tomcat
spec: 
 containers:
   - name: app
     image: imranvisualpath/freshtomapp:V7
     ports:
      - name: appport
        containerPort: 8080
