---
apiVersion: v1
kind: Service
metadata:
  name: nodesvc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
  selector:
    app: tomcatapp
